name: Notify Docs Repo

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to docs repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: gjb8114/gjb8114.github.io
          event-type: clang-tidy-gjb8114-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'